"""
Proactive Events — Data structures for the proactive behavior engine.
"""
from dataclasses import dataclass, field
from enum import IntEnum
from typing import Any


class EventPriority(IntEnum):
    LOW = 0       # Jokes, random commentary
    NORMAL = 1    # Time-based events, idle detection
    HIGH = 2      # System warnings (CPU/RAM)
    CRITICAL = 3  # System critical (disk full, network down)


@dataclass
class ProactiveEvent:
    """A proactive event generated by a background monitor."""
    event_type: str           # e.g., "cpu_high", "idle", "joke", "morning_greeting"
    data: dict                # Context data for response generation
    priority: EventPriority = EventPriority.NORMAL
    cooldown: float = 300.0   # Seconds before same event type can fire again
    deliver_notification: bool = True  # Also send desktop notification
    timestamp: float = field(default_factory=lambda: __import__('time').time())
